// shopping cart action types
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_PRODUCT_QUANTITY = 'CHANGE_PRODUCT_QUANTITY';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

// catalogue action types
export const SET_ADDED_TO_CART = 'SET_ADDED_TO_CART';
export const SET_ALL_REMOVED_FROM_CART = 'SET_ALL_REMOVED_FROM_CART';
export const SET_REMOVED_FROM_CART = 'SET_REMOVED_FROM_CART';

// order action types
export const CLEAR_ORDER_ERROR = 'CLEAR_ORDER_ERROR';
export const CLEAR_SAVED_ORDER_INFO = 'CLEAR_SAVED_ORDER_INFO';
export const SAVE_ORDER_INFO = 'SAVE_ORDER_INFO';
export const SEND_ORDER_ERROR = 'SEND_ORDER_ERROR';
export const SEND_ORDER_PENDING = 'SEND_ORDER_PENDING';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
